### ISSUE TITLE
why nextbytes put data chunk into ByteSlicePool

### ISSUE THREAD

**Issue by chaosma** [ipfs/go-ipfs-chunker#1]
I try to understand how ipfs works.  When ipfs add a file, the splitter in splitting.go will return a chunk of file each time NextBytes() is called. But why it also add that chunk into ByteSlicePool?  What's the purpose of ByteSlicePool?

**Comment by Stebalien** [comment]
The byte slice pool is a buffer pool to help us avoid allocations.

1. It *gets* chunk-sized buffer from the buffer pool.
2. If it reads less than a full chunk, it copies the data to a smaller buffer (the size of the data), and returns the chunk-sized buffer to the pool.
3. On error, NextBytes always returns the buffer to the pool.

The original motivation for this was:

1. When reading large files, we would like to allocate once per chunk. This means we need to allocate a full chunk-sized buffer up-front.
2. When reading a small file, we don't want to keep the large buffer around (kills memory usage). Therefore, we copy to a smaller buffer. However, we don't want to allocate and then throw away a bunch of large buffers when reading small files. GC tends to lag a bit so this wastes a lot of memory. Therefore, we always try to put these large buffers back into the pool so we can reuse them when possible.

**Comment by chaosma** [comment]
Thanks for the comments!  Is my following understanding correct:

Each time we call NextBytes(), it can reuse the allocated memory in the buffer pool which will save allocation time because each chunk has the same size. Since we always put large buffers back, the number of chunked buffers in the pool depends on (the number is similar or equal to) how many threads are using this pool. The allocated buffers (the number depends on the peak usage) in the pool are always stayed in memory until the program is killed.

**Comment by Stebalien** [comment]
Not quite. When we *return* a large buffer, we can't put it back because we've given it away. Unfortunately, there's not much we can do about this.

**Comment by chaosma** [comment]
I see in the code that for large buffer, it is thrown away. Why not put it back for re-use? If for each chunk, it will allocate a buffer once, I don't understand how it will speed up the process. Suppose we don't use the the pool, we can still create a byte slice (like in small case) and return.  Thanks!

**Comment by Stebalien** [comment]
> I see in the code that for large buffer, it is thrown away. Why not put it back for re-use?

It's never thrown away, it's returned. We're using the buffer pool to optimize the small case, not the large case.
