### ISSUE TITLE
Make buzhash tunable like rabin?

### ISSUE THREAD

**Issue by Artoria2e5** [ipfs/go-ipfs-chunker#25]
Since buzhash is supposed to work like rabin but be faster, it might make sense to add some tunablilty to it like we are already doing for rabin.

From my awful understanding of this code, I want you to:
* Put buzMin, buzMax, buzMask in the Buzhash struct
* Make a NewBuzhashMinMax constructor that calculates `buzmask` using some log2 business
* Change the parser to use rabin parsing

**Comment by momack2** [comment]
I don't think we plan to extend buzhash at this time, but you may be interested in DAGger - a chunker evaluation tool created by @ribasushi: https://github.com/ipfs/DAGger

**Comment by Artoria2e5** [comment]
Yeah, I agree that there isn't much point in it anyways.
